### PR TITLE
pass *args and **kwargs into str methods for all a{r,c}b_* and expand goodstr domain

### PR DESCRIPTION
**Pull request by edgarcosta**

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Does this affect anything that could be testable or is it just for consistency?

**Comment by edgarcosta** [comment]
It enables something like:
```
showgood(lambda : acb_series([arb.pi(), (arb.pi() + arb("1e-100")).sin()]), maxprec=10**3)
3.14159265358979 + (-1.00000000000000e-100)*x + O(x^10)
```
before you would have to use:
```
showgood(lambda : acb_series([arb.pi(), (arb.pi() + arb("1e-100")).sin()]).coeffs(), maxprec=10**3)
[3.14159265358979, -1.00000000000000e-100]
```
otherwise you would trigger:
```
raise TypeError("must have arb or acb")
```

**Comment by edgarcosta** [comment]
Here is a more realistic example:
```python3
>>> from flint import *
>>> z = acb(1+1j); tau = acb(1.25+3j)
>>> showgood(lambda: acb_mat([[tau]]).theta(acb_mat([[z]])).transpose(), dps=25)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "showgood.pyx", line 131, in flint.functions.showgood.showgood
  File "showgood.pyx", line 108, in flint.functions.showgood.good
  File "showgood.pyx", line 39, in flint.functions.showgood.goodstr
TypeError: must have arb or acb

**Comment by oscarbenjamin** [comment]
Okay, I see. Looks good!

**Pull request merged**
