### PR TITLE
Add prerelease testing for CPython 3.13 to CI

### PR DESCRIPTION
**Pull request by oscarbenjamin**
Add prerelease testing for CPython 3.13 to CI

It would also be good to add a job that builds flint from git trunk...

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Looks like building against flint main fails for `fmpz_mod_mat`:
```
src/flint/types/fmpz_mod_mat.c:4860:5: error: too few arguments to function ‘fmpz_mod_mat_clear’
       4860 |     fmpz_mod_mat_clear(__pyx_v_self->val);
            |     ^~~~~~~~~~~~~~~~~~
      In file included from src/flint/types/fmpz_mod_mat.c:1227:
      /usr/local/include/flint/fmpz_mod_mat.h:48:6: note: declared here
         48 | void fmpz_mod_mat_clear(fmpz_mod_mat_t mat, const fmpz_mod_ctx_t ctx);
            |      ^~~~~~~~~~~~~~~~~~
```
Maybe there are incompatible changes to the signatures of functions that operate with `fmpz_mod_mat`...

**Comment by oscarbenjamin** [comment]
Looks like this was changed in https://github.com/flintlib/flint/pull/1754

**Comment by fredrik-johansson** [comment]
> Looks like this was changed in [flintlib/flint#1754](https://github.com/flintlib/flint/pull/1754)

Yes, this will be a notable compatibility-breaking change in 3.1. There could be others, but hopefully nothing as major.

**Comment by oscarbenjamin** [comment]
I don't think it would be hard to change the `fmpz_mod_mat` code in python-flint for the change. Attempting to support both versions of Flint is possibly awkward but perhaps this is a good moment to see how well an `#ifdef` approach can work.

**Comment by oscarbenjamin** [comment]
The python-flint fmpz_mod_mat type already stores a reference to an associated
`fmpz_mod_ctx`. If I understand correctly the change is mostly just that almost
all `fmpz_mod_mat` functions in flint now need this ctx to be passed explicitly
as an additional parameter.

We can probably do something like:
```cython
# fmpz_mod_mat.pxd
cdef extern from *:
    """
    /*
     * fmpz_mod_mat function signatures were changed in flint 3.1.0
    */
    #if __FLINT_RELEASE >= 30100
    void fmpz_mod_mat_clear_compat(fmpz_mod_mat_t mat, fmpz_mod_ctx_t ctx) {
        fmpz_mod_mat_clear(mat, ctx);
    }
    #else
    void fmpz_mod_mat_clear_compat(fmpz_mod_mat_t mat, fmpz_mod_ctx_t ctx) {
        fmpz_mod_mat_clear(mat);
    }
    #endif
    """

cdef extern from "flint/fmpz_mod_mat.h":
    void fmpz_mod_mat_clear_compat(fmpz_mod_mat_t mat, fmpz_mod_ctx_t ctx)

# fmpz_mod_mat.pyx
cdef class fmpz_mod_mat:
    ...
    def __dealloc__(self):
        fmpz_mod_mat_clear_compat(self.mat, self.ctx)
```

**Comment by oscarbenjamin** [comment]
Okay, all sorted and works with latest Flint from git as well as previous versions.

**Pull request merged**
