### PR TITLE
Bump to Flint version 3

### PR DESCRIPTION
**Pull request by GiacomoPope**
This PR follows #43 but from the latest commits to master avoiding conflicts.

### CODE REVIEW

**Comment by GiacomoPope** [comment]
Hmm some things are now failing, so I imagine I've messed up this PR. I'll work through the error messages.

```
Error: Command ['python', '-m', 'pip', 'wheel', PurePosixPath('/project'), '--wheel-dir=/tmp/cibuildwheel/built_wheel', '--no-deps'] failed with code 1. 

Checking for common errors...
Error: Process completed with exit code 1.
```

Doesn't look like the most helpful message though! :D

**Comment by GiacomoPope** [comment]
> You have to expand the little triangle on the line that says "Building wheel..." to see the build failures from cibuildwheel in GitHub Actions

Yeah I had just done that and I've pushed a fix, thanks for the help

**Comment by GiacomoPope** [comment]
Hmm the tests on the CI pass but I seem to have some issues locally, not 100% sure this is ready yet

**Comment by oscarbenjamin** [comment]
> Maybe I just have some flint2 and flint3 polluting things.

It is better to keep a local build of Flint etc for python-flint development. That is why the build scripts build in .local which also means that you can just `rm -rf .local` any time you want to start again.

**Comment by GiacomoPope** [comment]
Yeah I have deleted the `.local` and all the errors are the same (you can see that in the error inlucded from... error. Not really sure what the issue could be.

**Comment by GiacomoPope** [comment]
Has it just got to do with the cython names colliding with the C ones? e.g. this line in the scarping script:

```
# rename types to avoid python -- c name collisions
rename_types = [(re.compile(r"\bfmpz\b"),"fmpz_struct"),(re.compile(r"\bfmpq\b"), "fmpq_struct")]
```

**Comment by oscarbenjamin** [comment]
You have a build of Flint in `/usr/local`.
```
.local/include/flint/fmpz_types.h:29:1: error: typedef redefinition with different types ('struct fmpz_factor_struct' vs 'struct fmpz_factor_struct')
fmpz_factor_struct;
^
/usr/local/include/flint/fmpz_factor.h:35:3: note: previous definition is here
```
This is being picked up somehow.

**Comment by oscarbenjamin** [comment]
I don't see the `nmod_poly_factor.pxd` file in this PR.

**Comment by GiacomoPope** [comment]
It's this file: https://github.com/GiacomoPope/python-flint/blob/flint3/src/flint/flintlib/nmod_poly_factor.pxd

Or am I missing something inside `/types/`?

**Comment by oscarbenjamin** [comment]
Oh, yes it was added separately

**Comment by oscarbenjamin** [comment]
I think that the errors that you see are just because you have a Flint 2 installed into `/usr/local`. Maybe remove that and try again.

**Comment by GiacomoPope** [comment]
If I uninstall the `/local/` flint and compile I get no errors but when running the tests I get a weird error:

```
Jack: python-flint % python3 -m flint.test --tests                                                               
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/Jack/Documents/GitHub/python-flint/src/flint/__init__.py", line 1, in <module>
    from .pyflint import *
ImportError: dlopen(/Users/Jack/Documents/GitHub/python-flint/src/flint/pyflint.cpython-311-darwin.so, 0x0002): Library not loaded: /usr/local/opt/flint/lib/libflint-17.dylib
  Referenced from: <BE5AA1EA-63E8-34DA-A9CA-D471A88D424F> /Users/Jack/Documents/GitHub/python-flint/src/flint/pyflint.cpython-311-darwin.so
  Reason: tried: '/usr/local/opt/flint/lib/libflint-17.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/flint/lib/libflint-17.dylib' (no such file), '/usr/local/opt/flint/lib/libflint-17.dylib' (no such file), '/usr/local/lib/libflint-17.dylib' (no such file), '/usr/lib/libflint-17.dylib' (no such file, not in dyld cache)
  ```
  
I have no idea why the changes made would be doing this and don't have that much time to debug my side tonight

**Comment by oscarbenjamin** [comment]
You need to remove the runtime shared libraries as well as the header files before recompiling:
```python
$ ls .local/lib/
libarb.so         libflint.so.17      libgmp.la         libmpfr.la        pkgconfig
libarb.so.2       libflint.so.17.0.0  libgmp.so         libmpfr.so
libarb.so.2.14.0  libflint.so.18      libgmp.so.10      libmpfr.so.6
libflint.so       libflint.so.18.0.0  libgmp.so.10.4.1  libmpfr.so.6.1.0
```
What does `ls /usr/local/lib` show?

**Comment by GiacomoPope** [comment]
I'll have an explore tomorrow but I'm really confused about exactly what has caused this to break, unless everything was always drawing from /local/ for me and now the breakage is that I used to have 2.9 and now have 3.0...

**Comment by GiacomoPope** [comment]
```
Jack: python-flint % python3 -m flint.test --tests 
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/local/lib/python3.11/site-packages/flint/__init__.py", line 1, in <module>
    from ._flint import *
ImportError: dlopen(/usr/local/lib/python3.11/site-packages/flint/_flint.cpython-311-darwin.so, 0x0002): Library not loaded: /usr/local/opt/flint/lib/libflint-17.dylib
  Referenced from: <5EFCA8B1-9B60-31D4-8A6F-02CD2C23527E> /usr/local/lib/python3.11/site-packages/flint/_flint.cpython-311-darwin.so
  Reason: tried: '/usr/local/opt/flint/lib/libflint-17.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/flint/lib/libflint-17.dylib' (no such file), '/usr/local/opt/flint/lib/libflint-17.dylib' (no such file), '/usr/local/lib/libflint-17.dylib' (no such file), '/usr/lib/libflint-17.dylib' (no such file, not in dyld cache)
Jack: python-flint % ls .local/lib
libflint.18.0.dylib* libflint.dylib@      libgmp.dylib@        libmpfr.6.dylib*     libmpfr.la*
libflint.18.dylib@   libgmp.10.dylib*     libgmp.la*           libmpfr.dylib@       pkgconfig/
```

So this must all just boil down to polluted paths and stuff, but it makes it really annoying from the dev point of view. There must be a way to cythonize so it *only* looks in `.local` but I haven't found something via googling yet.

**Comment by oscarbenjamin** [comment]
Okay, looks good!

Let's get this in so we don't have to resolve merge conflicts for a fourth time.

**Pull request merged**
